export const supportTitles = {
  privacy: 'Privacy Policy', terms: 'Terms & Conditions', shipping: 'Shipping Policy',
  returns: 'Return & Refund Policy', contact: 'Contact / Support', faq: 'FAQ',
} as const
export type SupportPage = keyof typeof supportTitles
export function supportPageFromHash(hash: string): SupportPage | null {
  const key = hash.replace(/^#\//, '')
  return Object.hasOwn(supportTitles, key) && hash.startsWith('#/') ? key as SupportPage : null
}
export function contactLinks(settings: { business_email?: string | null; whatsapp_number?: string | null }) {
  const email = settings.business_email?.trim() ?? ''
  const number = settings.whatsapp_number?.trim() ?? ''
  const digits = number.replace(/[^0-9]/g, '')
  return {
    email: /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email) ? { label: email, href: `mailto:${encodeURIComponent(email)}` } : null,
    whatsapp: /^\+?[0-9 ()-]+$/.test(number) && digits.length >= 7 && digits.length <= 15 ? { label: number, href: `https://wa.me/${digits}` } : null,
  }
}
export const supportContent: Record<Exclude<SupportPage, 'contact'>, Array<[string, string]>> = {
  privacy: [
    ['Information you provide', 'We use the account details you provide, including your name, email and sign-in information, to manage your account. Checkout and order records include delivery details, contact information, products and selected options, quantities, totals and payment status. Support messages and payment receipts you choose to share help us respond and verify payment.'],
    ['How information is used', 'We use this information to operate your account, process and fulfil orders, provide order updates, answer support requests and protect the website against misuse. Please do not send passwords, sign-in codes or full payment-card details through support channels.'],
    ['Services that help operate the store', 'Supabase supports account authentication and data storage. Our hosting provider delivers the website, and an email service delivers transactional order messages. Delivery and support providers may receive the information needed to fulfil your order or respond to you. WhatsApp and your email provider also process messages you send through their services. Service providers may process information outside Canada.'],
    ['Browser storage and technical information', 'The storefront uses browser storage to keep you signed in, remember your bag and protect against duplicate checkout attempts. Hosting and other website services may process technical request information, such as IP addresses and browser information, to deliver and secure the site. Loading externally hosted images and fonts also sends requests to those providers. This policy does not describe advertising tracking or analytics features as part of the current storefront.'],
    ['Keeping and protecting records', "We retain personal information only as long as reasonably necessary for the purposes for which it was collected and applicable obligations, then delete or anonymize it where appropriate. Some information may need to be retained for order and transaction records, legal, accounting or tax obligations, security or fraud prevention. There is no fixed retention period for all records. Access controls help restrict account and order information. No online service can promise absolute security."],
    ['Your questions and requests', "Use the business email listed on Contact / Support for privacy requests, including access, correction or deletion of your personal information. We may need to verify your identity. Where information must be retained for reasonably necessary records or obligations, we will explain relevant limits on deletion."],
  ],
  terms: [
    ['Using the store', 'Use Bali & Lisa Glam for lawful shopping and account activity. Keep your sign-in details private and do not attempt to interfere with the website or access another customer’s account.'],
    ['Orders and manual payment', 'Placing an order records your request and may reserve available stock. It does not mean payment has been received or verified. Follow the payment instructions provided through the store’s email or WhatsApp channel. Payment remains awaiting confirmation until the business independently verifies it. An order receipt is not proof of payment or dispatch. Contact Support if an order cannot be fulfilled.'],
    ['Prices and availability', 'Prices and order totals are in Canadian dollars (CAD). Review the products, selected options, quantities, shipping and total before submitting. Availability and prices can change before an order is placed. If an error or fulfilment issue affects your order, we will contact you to discuss the next step rather than assume your agreement to a substitution or revised charge.'],
    ['Delivery details and international orders', "Provide an accurate, complete delivery address and contact details. Ask Support promptly about corrections; changes may not be possible after dispatch. International customers are responsible for applicable customs duties, import taxes, brokerage charges or similar destination-country charges, separate from our product and shipping charges. Check destination requirements before ordering."],
    ['Product information', 'Read the product description, options and packaging instructions. Screen colours can differ from the physical product. Cosmetic descriptions are not medical advice or promises to treat a condition. We do not promise a particular appearance or result, and statements made outside our published product information are not additional product guarantees.'],
    ['Policies and customer rights', 'Read the Shipping and Return & Refund policies before ordering. These terms do not exclude rights or remedies that cannot be excluded under applicable consumer law. Contact Support about errors, product concerns or disputes.'],
  ],
  shipping: [
    ['Canada and international destinations', "Bali & Lisa Glam ships within Canada and internationally to supported destinations worldwide. If checkout cannot quote shipping for your destination, contact Support before placing or paying for an order."],
    ['Rates and free shipping', 'Review the shipping amount and total shown at checkout. Free shipping applies only when configured for your destination and your order meets the applicable threshold. Do not assume a Canada shipping offer applies internationally.'],
    ['Processing and delivery', "Orders are normally prepared and dispatched within 1–2 business days after payment confirmation. Estimated delivery within Canada is 1–3 business days after dispatch. International delivery is estimated at up to 14 business days after dispatch. These estimates are not guarantees and may be affected by the destination, carrier operations, customs and circumstances outside Bali & Lisa Glam’s reasonable control. Contact Support before ordering if you need delivery by a particular date."],
    ['International charges', "International customers are responsible for applicable customs duties, import taxes, brokerage charges or similar destination-country charges. These are separate from the store’s product and shipping charges. Check destination requirements before ordering. Customs checks may delay delivery."],
    ['Accurate addresses', 'Check your address, unit number, postal or ZIP code, country and contact details before submitting. Contact Support promptly if a correction is needed. We cannot promise an address change or redirection once an order has been dispatched; any available options and charges must be confirmed.'],
    ['Delayed, missing or damaged parcels', 'Contact Support with your order number and a description of the issue. If available, include tracking information and relevant packaging photos, avoiding unnecessary personal information. Keep packaging while the issue is reviewed. We will review the shipment with you and, where appropriate, the carrier before confirming available next steps.'],
  ],
  returns: [
    ['Ask before returning an item', "Return requests must be made within 7 days of delivery. Contact Support with your order number, the item and the reason for your request. Do not send products back before receiving return instructions."],
    ['Condition and eligibility', "Eligible products must be unused, unopened and in their original packaging. Opened or used cosmetics are final sale for hygiene reasons, except when an item arrived damaged or defective, or Bali & Lisa Glam sent the wrong item. These conditions do not remove rights under applicable consumer law."],
    ['Damaged, incorrect or faulty items', "Contact Support if an item arrived damaged or defective, or we sent the wrong item. Describe the issue and provide relevant photos if available. Bali & Lisa Glam covers reasonable return or replacement shipping costs in these cases. Hygiene or final-sale restrictions do not remove rights you have under applicable consumer law."],
    ['Refunds and return shipping', "For an otherwise eligible change-of-mind return, the customer is responsible for return shipping. Once an eligible return is received and approved, we refund using the original payment method where possible. If that is not possible because of the manual payment method used, Bali & Lisa Glam and the customer may agree on an appropriate refund method. Refund processing can depend on the payment provider; no guaranteed processing deadline is offered."],
    ['Order cancellations', "Customers may request cancellation before an order has been dispatched. Contact Support promptly with your order number. Once dispatched, an order cannot be cancelled and this Return & Refund Policy applies instead."],
  ],
  faq: [
    ['Can I cancel an order?', 'You may request cancellation before dispatch. Once dispatched, the order cannot be cancelled and the Return & Refund Policy applies. Contact Support promptly with your order number.'],
    ['How do I place an order?', 'Choose your products and all required options, add them to your bag, then sign in and complete checkout. Review your delivery details, quantities, shipping and CAD total before placing the order.'],
    ['Which payment methods are available?', 'The current checkout uses manual payment coordinated through WhatsApp or email. Follow the instructions provided by the business. Card checkout is not currently available.'],
    ['How is payment confirmed?', 'Placing an order does not mark it paid. Send your receipt through the chosen support channel after following payment instructions. The business verifies payment before marking the order paid. An order-received email is separate from a payment-confirmation email.'],
    ['Do you ship within Canada and internationally?', "Yes, within Canada and to supported destinations worldwide. Orders are normally dispatched within 1–2 business days after payment confirmation. Estimated delivery after dispatch is 1–3 business days within Canada and up to 14 business days internationally. Estimates are not guarantees; destination, carrier operations, customs and circumstances outside our reasonable control may affect delivery. Review checkout rates and our Shipping Policy. International customers are responsible for applicable duties, import taxes, brokerage and similar destination charges."],
    ['What currency do you use?', 'Product prices and order totals are in Canadian dollars (CAD). Your payment provider may apply its own currency-conversion charges.'],
    ['Where can I check my order status?', 'Sign in, open My account and select Orders to review payment and order status. If a status is unclear or an expected message has not arrived, contact Support with your order number.'],
    ['Can I change my delivery details?', 'Contact Support promptly with your order number. Updating your saved account address does not change an existing order. A correction may not be possible after dispatch.'],
    ['Can I return a product or request a refund?', "Request a return within 7 days of delivery. Eligible products must be unused, unopened and in their original packaging. Opened or used cosmetics are final sale except for items that arrived damaged or defective, or wrong items we sent. We cover reasonable return/replacement shipping for those exceptions; customers pay shipping for eligible change-of-mind returns. Approved returns are refunded after receipt, using the original payment method where possible or an agreed alternative where the manual payment method prevents this. Read the Return & Refund Policy before sending anything back."],
    ['How do I contact you?', 'Use the current business email or WhatsApp link on Contact / Support. Include your order number when relevant, but never send passwords, sign-in codes or full card details.'],
  ],
}
