-- READ ONLY. Actual production metadata, never migration history or customer PII.
-- Use a read-only transaction or the Management API read-only query endpoint.
select jsonb_build_object(
 'aggregate', (select jsonb_build_object('orders',(select count(*) from public.orders),'items',(select count(*) from public.order_items),'negative_stock',(select count(*) from public.products where inventory_quantity<0),'mismatched_totals',(select count(*) from public.orders where total_cents<>subtotal_cents+shipping_cents),'empty_orders',(select count(*) from public.orders o where not exists(select 1 from public.order_items i where i.order_id=o.id)))),
 'tables', (select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v','m')),
 'grants', (select jsonb_agg(x) from (select c.relname as table_name,r.role,p.privilege,has_table_privilege(r.role,c.oid,p.privilege) as allowed from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join (values ('anon'),('authenticated'),('service_role')) r(role) cross join (values ('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER'),('MAINTAIN')) p(privilege) where n.nspname='public' and c.relkind in ('r','p','v','m')) x),
 'column_grants', (select jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'acl',a.attacl)) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and a.attnum>0 and not a.attisdropped and a.attacl is not null),
 'schema_grants', (select jsonb_agg(jsonb_build_object('role',r.role,'create_public',has_schema_privilege(r.role,'public','CREATE'),'temp',has_database_privilege(r.role,current_database(),'TEMP'))) from (values ('anon'),('authenticated')) r(role)),
 'policies', (select jsonb_agg(p) from pg_policies p where schemaname in ('public','storage')),
 'functions', (select jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl,'definition',pg_get_functiondef(p.oid),'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind='f'),
 'triggers', (select jsonb_agg(jsonb_build_object('table',c.relname,'definition',pg_get_triggerdef(t.oid))) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal),
 'constraints', (select jsonb_agg(jsonb_build_object('table',c.relname,'name',t.conname,'definition',pg_get_constraintdef(t.oid))) from pg_constraint t join pg_class c on c.oid=t.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'),
 'sequences', (select jsonb_agg(jsonb_build_object('name',c.relname,'acl',c.relacl,'anon_usage',has_sequence_privilege('anon',c.oid,'USAGE'),'anon_update',has_sequence_privilege('anon',c.oid,'UPDATE'),'auth_usage',has_sequence_privilege('authenticated',c.oid,'USAGE'),'auth_update',has_sequence_privilege('authenticated',c.oid,'UPDATE'))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='S'),
 'defaults', (select jsonb_agg(d) from pg_default_acl d),
 'roles', (select jsonb_agg(jsonb_build_object('role',rolname,'superuser',rolsuper,'bypass_rls',rolbypassrls)) from pg_roles where rolname in ('anon','authenticated','service_role')),
 'buckets', (select jsonb_agg(jsonb_build_object('id',id,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types)) from storage.buckets where id='product-images')
) as audit;
